CP	= cp
RM	= rm
XA	= xa
EMURAM	= 17152

.SUFFIXES: .asm .o .prg

tasks.prg: tasks.asm 6o6.o harness.o payload1.o payload2.o
	$(XA) -o $@ -DCONFIGFILE=c64.def -DHSTUB=harness.def -DC64=1 \
		-DEMURAM=$(EMURAM) \
		-a -O PETSCII -P $@.lst \
		-l $@.sym tasks.asm
	$(CP) $@ ~/c64/prg || echo "Never mind."

.asm.o:
	$(XA) -o $@ -DCONFIGFILE=c64.def -DHSTUB=harness.def -DC64=1 \
		-DEMURAM=$(EMURAM) \
		-a -O PETSCII \
		-l $@.sym $<

clean:
	$(RM) -f *.o *.sym *.lst *.prg
