.PHONY: default c64 a2

default:
	@echo Enter "'"make c64"'" or "'"make a2"'"

c64:
	$(MAKE) -f Makefile.c64

a2:
	$(MAKE) -f Makefile.a2

clean:
	$(MAKE) -f Makefile.c64 clean
	$(MAKE) -f Makefile.a2 clean

